[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.light"

[deploy]
healthcheckPath = "/"
restartPolicyType = "never"

[[services]]
name = "chart-coordinator"

[services.healthcheck]
path = "/"
intervalSeconds = 300
timeoutSeconds = 10 